wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718501481.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.12.1
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 5000
epochs:
  desc: null
  value: 10
patience:
  desc: null
  value: 5
